version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_user_prod
      - POSTGRES_PASSWORD=postgres_user_prod_password
      - POSTGRES_DB=postgres_db_prod

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data_prod: